-- ============================================================
-- Migration 0001 — Core schema
-- Every table uses TEXT UUIDs as primary keys (generated by the
-- app layer), ISO-8601 timestamps, and soft-delete via
-- `deleted_at`.  See /docs/database/ for the full specification.
-- ============================================================

-- ── lists ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lists (
    id          TEXT    PRIMARY KEY,
    name        TEXT    NOT NULL,
    color       TEXT,                   -- hex colour for UI badge
    icon        TEXT,                   -- emoji or icon slug
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    deleted_at  TEXT
);

-- ── tasks ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tasks (
    id          TEXT    PRIMARY KEY,
    title       TEXT    NOT NULL,
    notes       TEXT,
    list_id     TEXT    REFERENCES lists(id) ON DELETE SET NULL,
    due_at      TEXT,                   -- ISO-8601 datetime, nullable
    is_done     INTEGER NOT NULL DEFAULT 0 CHECK (is_done IN (0, 1)),
    done_at     TEXT,
    priority    INTEGER NOT NULL DEFAULT 0, -- 0=none 1=low 2=medium 3=high
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    deleted_at  TEXT
);

CREATE INDEX IF NOT EXISTS idx_tasks_list_id  ON tasks (list_id)  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_due_at   ON tasks (due_at)   WHERE deleted_at IS NULL AND is_done = 0;
CREATE INDEX IF NOT EXISTS idx_tasks_is_done  ON tasks (is_done)  WHERE deleted_at IS NULL;

-- ── routines ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS routines (
    id          TEXT    PRIMARY KEY,
    name        TEXT    NOT NULL,
    recurrence  TEXT    NOT NULL,       -- 'daily' | 'weekdays' | 'weekly:<DOW>' | 'custom:<cron>'
    active      INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    deleted_at  TEXT
);

-- ── routine_items ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS routine_items (
    id          TEXT    PRIMARY KEY,
    routine_id  TEXT    NOT NULL REFERENCES routines(id) ON DELETE CASCADE,
    title       TEXT    NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    deleted_at  TEXT
);

CREATE INDEX IF NOT EXISTS idx_routine_items_routine ON routine_items (routine_id) WHERE deleted_at IS NULL;

-- ── routine_completions ──────────────────────────────────────
-- One row per (item, calendar-date).  Idempotent upsert on conflict.
CREATE TABLE IF NOT EXISTS routine_completions (
    id          TEXT    PRIMARY KEY,
    item_id     TEXT    NOT NULL REFERENCES routine_items(id) ON DELETE CASCADE,
    date        TEXT    NOT NULL,       -- 'YYYY-MM-DD'
    completed_at TEXT   NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    UNIQUE (item_id, date)
);

CREATE INDEX IF NOT EXISTS idx_routine_completions_date ON routine_completions (date);

-- ── focus_sessions ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS focus_sessions (
    id              TEXT    PRIMARY KEY,
    task_id         TEXT    REFERENCES tasks(id) ON DELETE SET NULL,
    started_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    ended_at        TEXT,
    planned_minutes INTEGER NOT NULL DEFAULT 25,
    actual_minutes  INTEGER,
    interrupted     INTEGER NOT NULL DEFAULT 0 CHECK (interrupted IN (0, 1)),
    notes           TEXT
);

CREATE INDEX IF NOT EXISTS idx_focus_sessions_started ON focus_sessions (started_at);
CREATE INDEX IF NOT EXISTS idx_focus_sessions_task    ON focus_sessions (task_id) WHERE task_id IS NOT NULL;

-- ── reminders ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reminders (
    id          TEXT    PRIMARY KEY,
    task_id     TEXT    REFERENCES tasks(id) ON DELETE CASCADE,
    remind_at   TEXT    NOT NULL,       -- ISO-8601 datetime
    fired       INTEGER NOT NULL DEFAULT 0 CHECK (fired IN (0, 1)),
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_reminders_remind_at ON reminders (remind_at) WHERE fired = 0;

-- ── plugin_storage ───────────────────────────────────────────
-- Isolated key-value store for plugins.  Each plugin gets its own namespace.
CREATE TABLE IF NOT EXISTS plugin_storage (
    plugin_id   TEXT    NOT NULL,
    key         TEXT    NOT NULL,
    value       TEXT    NOT NULL,       -- JSON-serialised
    updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    PRIMARY KEY (plugin_id, key)
);
